"""initial application schema

Revision ID: d046b2eba9b3
Revises:
Create Date: 2026-10-04 22:45:40.801039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd046b2eba9b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.Column('net_liquidation', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('buying_power', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_node', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_captured_at'), 'account_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_account_snapshots_mode'), 'account_snapshots', ['mode'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=120), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('data_source_status',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('node', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_date', sa.String(length=10), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_status_status'), 'data_source_status', ['status'], unique=False)
    op.create_table('job_status',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_status_status'), 'job_status', ['status'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('remote_addr', sa.String(length=80), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_remote_addr'), 'login_attempts', ['remote_addr'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=80), nullable=False),
    sa.Column('asset_class', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('thesis_md', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('execution_status', sa.String(length=80), nullable=False),
    sa.Column('spec_path', sa.String(length=500), nullable=False),
    sa.Column('current_version', sa.String(length=120), nullable=False),
    sa.Column('live_eligible', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_execution_status'), 'strategies', ['execution_status'], unique=False)
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('delivered_wechat', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_acknowledged'), 'alerts', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_strategy_id'), 'alerts', ['strategy_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=96), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('remote_addr', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('execution_authorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('notional_cap_usd', sa.Float(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_authorizations_expires_at'), 'execution_authorizations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_execution_authorizations_mode'), 'execution_authorizations', ['mode'], unique=False)
    op.create_index(op.f('ix_execution_authorizations_status'), 'execution_authorizations', ['status'], unique=False)
    op.create_index(op.f('ix_execution_authorizations_strategy_id'), 'execution_authorizations', ['strategy_id'], unique=False)
    op.create_table('position_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('average_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['account_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_snapshots_snapshot_id'), 'position_snapshots', ['snapshot_id'], unique=False)
    op.create_table('progress_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_events_strategy_id'), 'progress_events', ['strategy_id'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=True),
    sa.Column('assessment', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(length=40), nullable=False),
    sa.Column('user_decision', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_status'), 'research_notes', ['status'], unique=False)
    op.create_index(op.f('ix_research_notes_strategy_id'), 'research_notes', ['strategy_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_start', sa.String(length=10), nullable=True),
    sa.Column('data_end', sa.String(length=10), nullable=True),
    sa.Column('as_of_date', sa.String(length=10), nullable=True),
    sa.Column('code_version', sa.String(length=80), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('artifact_path', sa.String(length=800), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_as_of_date'), 'research_runs', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_research_runs_run_type'), 'research_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_research_runs_source_hash'), 'research_runs', ['source_hash'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_index(op.f('ix_research_runs_strategy_id'), 'research_runs', ['strategy_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_version_unique', 'strategy_versions', ['strategy_id', 'version'], unique=True)
    op.create_index(op.f('ix_strategy_versions_config_hash'), 'strategy_versions', ['config_hash'], unique=False)
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('execution_plans',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('authorization_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('data_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('total_notional_usd', sa.Float(), nullable=False),
    sa.Column('orders', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authorization_id'], ['execution_authorizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_plans_authorization_id'), 'execution_plans', ['authorization_id'], unique=False)
    op.create_index(op.f('ix_execution_plans_mode'), 'execution_plans', ['mode'], unique=False)
    op.create_index(op.f('ix_execution_plans_status'), 'execution_plans', ['status'], unique=False)
    op.create_index(op.f('ix_execution_plans_strategy_id'), 'execution_plans', ['strategy_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.String(length=250), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('benchmark', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_unique', 'metrics', ['run_id', 'scope', 'name'], unique=True)
    op.create_index(op.f('ix_metrics_run_id'), 'metrics', ['run_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('as_of_date', sa.String(length=10), nullable=False),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('artifact_path', sa.String(length=800), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_reports_as_of_date'), 'research_reports', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_research_reports_content_hash'), 'research_reports', ['content_hash'], unique=False)
    op.create_index(op.f('ix_research_reports_report_type'), 'research_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_research_reports_run_id'), 'research_reports', ['run_id'], unique=False)
    op.create_index(op.f('ix_research_reports_strategy_id'), 'research_reports', ['strategy_id'], unique=False)
    op.create_table('order_records',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('plan_id', sa.String(length=100), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('average_fill_price', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_records_broker_order_id'), 'order_records', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_order_records_plan_id'), 'order_records', ['plan_id'], unique=False)
    op.create_index(op.f('ix_order_records_status'), 'order_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_records_status'), table_name='order_records')
    op.drop_index(op.f('ix_order_records_plan_id'), table_name='order_records')
    op.drop_index(op.f('ix_order_records_broker_order_id'), table_name='order_records')
    op.drop_table('order_records')
    op.drop_index(op.f('ix_research_reports_strategy_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_run_id'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_report_type'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_content_hash'), table_name='research_reports')
    op.drop_index(op.f('ix_research_reports_as_of_date'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_metrics_run_id'), table_name='metrics')
    op.drop_index('ix_metric_unique', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_execution_plans_strategy_id'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_status'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_mode'), table_name='execution_plans')
    op.drop_index(op.f('ix_execution_plans_authorization_id'), table_name='execution_plans')
    op.drop_table('execution_plans')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_config_hash'), table_name='strategy_versions')
    op.drop_index('ix_strategy_version_unique', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_research_runs_strategy_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_source_hash'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_run_type'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_as_of_date'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_research_notes_strategy_id'), table_name='research_notes')
    op.drop_index(op.f('ix_research_notes_status'), table_name='research_notes')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_progress_events_strategy_id'), table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_index(op.f('ix_position_snapshots_snapshot_id'), table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.drop_index(op.f('ix_execution_authorizations_strategy_id'), table_name='execution_authorizations')
    op.drop_index(op.f('ix_execution_authorizations_status'), table_name='execution_authorizations')
    op.drop_index(op.f('ix_execution_authorizations_mode'), table_name='execution_authorizations')
    op.drop_index(op.f('ix_execution_authorizations_expires_at'), table_name='execution_authorizations')
    op.drop_table('execution_authorizations')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_alerts_strategy_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_execution_status'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_remote_addr'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_job_status_status'), table_name='job_status')
    op.drop_table('job_status')
    op.drop_index(op.f('ix_data_source_status_status'), table_name='data_source_status')
    op.drop_table('data_source_status')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_account_snapshots_mode'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_captured_at'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
